name: CI

on:
  push:
    branches: master
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint

  abi-integrity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout subgraph
        uses: actions/checkout@v2
        with:
          path: subgraph
      - name: Checkout core
        uses: actions/checkout@v2
        with:
          repository: balancer-labs/balancer-core-v2
          token: ${{ secrets.PAT }}
          path: core
          ref: master
      - name: Install
        run: cd subgraph && yarn --frozen-lockfile
      - name: import abis
        run: cd subgraph && yarn import-abis
      - name: check abis
        run: cd subgraph && git diff HEAD --exit-code
env:
  CI: true
